export const EDU_PREP_PROGRAMS = [
	'ATDP (Academic Talent Development Program)',
	'boost@BerkeleyHaas',
	'California State Summer School for Mathematics and Science (COSMOS)',
	'Cal-SOAP',
	'CAMP (California Alliance for Minority Participation in Science)',
	'CBOP (Career Based Outreach Program)',
	'College Bound Academy Programs',
	'Council of African American Parents (CAAP)',
	'C-STEM',
	'Early Academic Outreach Program (EAOP)',
	'Educational Guidance Center (EGC)',
	'Educational Talent Search',
	'GEAR UP',
	'MESA (Mathematics, Engineering, Science Achievement) including MESA Schools Programs, SUCCESS Through Collaboration and California Community College Program',
	'PDP (Professional Development Program)',
	'Puente Program',
	'UC Links',
	'UC Merced Transfer Initiative Programs',
	'UC Scholars',
	'UCD Sacramento Area Youth Speaks (SAYS)',
	'UCLA Center for Community College Partnerships (CCCP)/SITE',
	'UCLA VIP Scholars Program',
	'UCSC SAGE (Students Acquiring "A-G" Expectations)',
	'UCSF Internships',
	'Upward Bound',
	'Wonderful Education',
	'Other'
];
